### ISSUE TITLE
Allow to close a window without removing its content

### ISSUE THREAD

**Issue by macqm** [rlamana/Ventus#18]
I would like to have option to sometimes close a window completely, rather than minimize, and be able to reopen it, without removing cached DOM of the window content.

**Comment by rlamana** [comment]
This is finally fixed in this commit: https://github.com/rlamana/Ventus/commit/bd7e13861f112949c7f9f40190950286689c73f5

Finally, default behaviour: just close without destroying. A new method 'destroy' can be called to do so. Check commit.

Event handlers can be added in Window constructor, so we can destroy windows on close doing this:
```javascript
wm.createWindow({
	title: 'Window ' + (num++),
	x: (pos += 60),
	y: pos,
	width: 400,
	height: 250,

	events: {
		closed: function() {
			this.destroy();
		}
	}
})
```

**Comment by macqm** [comment]
Great! Thanks, that's very helpful.

**Comment by DaniellMesquito** [comment]
I realise its a feature update, not a fix.
