### ISSUE TITLE
Window remains in drag state when mouse moved really quickly during dragging

### ISSUE THREAD

**Issue by macqm** [rlamana/Ventus#20]
Steps to reproduce:

1. Create a draggable window
2. Left click and hold the title bar to start moving the window
3. Now move mouse rather rapidly - notice window stopped being dragged, but the pointer continues to move outside the window area
4. Release the mouse button
5. Move the pointer back above the window

What I see:
Window stopped being moved and as soon as I go back with the mouse pointer above the window, dragging continues even though I don't hold left mouse button.

What I expected:
Either dragging continues until mouse button is released, or window stops moving, but is not in "dragging state".

I noticed it when working on Chrome 40, also reproduces on Safari, but I believe it's not something browser specific.

**Comment by rlamana** [comment]
I guess this is the expected behavior (not for a user) but given the technologies used here. So, the mouse button is released outside the browser window. The event ```mouseup``` is never captured by the browser since it happened within the boundaries of another desktop application. When the mouse pointer gets back to the browser the window state is still the same, but the user isn't pressing the button anymore.

A possible fix would be to check the buttons state in the ```mousemove``` event in order to refresh the real state of the window.
