### ISSUE TITLE
Touch events for mobile browsers

### ISSUE THREAD

**Issue by HighTechnological** [rlamana/Ventus#21]
window cant move
sorry for my english.

**Comment by rlamana** [comment]
Hi @HighTechnological,
A desktop window manager is actually not design to work on a mobile environment, so I'm not planning to support these browsers. However, it might be just a problem of the touch events instead of the mouse events. I'll take a look if I have the time.
Thanks for your comment anyway.

**Comment by rlamana** [comment]
@HighTechnological it should work now
