### ISSUE TITLE
Fullscreen button in windows

### ISSUE THREAD

**Issue by DaniellMesquita** [rlamana/Ventus#37]
This too will be usefull in "Video Player" window.

**Comment by rlamana** [comment]
Actually, I started implementing fullscreen window manager mode here: https://github.com/rlamana/Ventus/blob/master/src/ventus/wm/modes/fullscreen.js

Modes are important, because they behave like plugins that modify how the window manager works. Expose effect is done with one of this plugins: https://github.com/rlamana/Ventus/blob/master/src/ventus/wm/modes/expose.js

**Comment by rlamana** [comment]
I would say this is part of this other one: https://github.com/rlamana/Ventus/issues/37

**Comment by DaniellMesquita** [comment]
@rlamana , #37 is this same issue o.O

**Comment by amatiasq** [comment]
@DaniellMesquita I think he meant #38 which was renamed to include this issue.

**Comment by DaniellMesquito** [comment]
But that isn't the same thing. In #38 I'm suggesting to fullscreen mode be automatic for when mobile, and here I'm suggesting a Fullscreen button in windows, for users can enter into fullscreen mode directly from the window with the button.
@rlamana, please reopen and assign me to it.
