### ISSUE TITLE
Default/automatically fullscreen windows for when mobile

### ISSUE THREAD

**Issue by DaniellMesquito** [rlamana/Ventus#38]
Open windows defaulty/automatically in full screen for when mobile and easy tools to altern betwhen windows in mobile.

**Comment by rlamana** [comment]
Actually, I started implementing fullscreen window manager mode here: https://github.com/rlamana/Ventus/blob/master/src/ventus/wm/modes/fullscreen.js

Modes are important, because they behave like plugins that modify how the window manager works. Expose effect is done with one of this plugins: https://github.com/rlamana/Ventus/blob/master/src/ventus/wm/modes/expose.js

**Comment by DaniellMesquita** [comment]
Will be good open windows in fullscreen as default for when mobile ;)

**Comment by DaniellMesquita** [comment]
Too, you can use an link in mobile to open exposé with options to swipe-down windows to close (swipe down to an box, will be an amazing effect).

**Comment by DaniellMesquita** [comment]
@rlamana I mean that fullscreen need to be default/automatically for when in mobile.

**Comment by DaniellMesquita** [comment]
Fullscreen automatically in mobile is a thing, fullscreen button for desktop is other thing. I suggest for you open the other issue and rename this #38.

**Comment by DaniellMesquita** [comment]
I suggest reopen the #37 issue.
