### ISSUE TITLE
Popunders

### ISSUE THREAD

**Issue by DaniellMesquito** [rlamana/Ventus#53]
Feature popunders feature like Windows and [WS.js](https://github.com/Software-js/WS.js) does.

> Windows' popunder:
<img src="http://i.stack.imgur.com/fv5MB.png">
> 

> WS.js' popunder:
<img src="http://i.imgur.com/gBPTBRK.png">
>

**Comment by DaniellMesquito** [comment]
@rlamana, please assign me to it.

**Comment by RyanRiffle** [comment]
@DaniellMesquito I don't think asking @rlamana to assign all of these tickets to you is going to help anything. Take some initiative and write the code. Then submit a pull request. It looks like if you wait for permission you will never get it to be honest.

**Comment by DaniellMesquito** [comment]
@RyanRiffle ask ramon to assign these tickets is a proof of activity, I don't want stop my work to do pull request that can be ignored.

**Comment by RyanRiffle** [comment]
@DaniellMesquito Hop on Gitter, we can talk there

**Comment by DaniellMesquito** [comment]
@RyanRiffle good idea. But ask Rámon here to assign me isn't considered a spam, is like any request in a social network.

**Comment by amatiasq** [comment]
I agree with @RyanRiffle, I don't see the point on asking for assignement.

I don't understand the "proof of activity" explanation I guess that if we are talking about Ventus again is because the activity this repository had last days including a merge of a pull request by rlamana.

Specially I don't understand asking for assignement on every single issue, I think that's spam.

**Comment by DaniellMesquito** [comment]
> I agree with @RyanRiffle, I don't see the point on asking for assignement.

I don't understand the "proof of activity" explanation I guess that if we are talking about Ventus again is because the activity this repository had last days including a merge of a pull request by rlamana.

Specially I don't understand asking for assignement on every single issue, I think that's spam.

Your agrees or disagress won't change my life and my humour. The point is comprove the activity or if Rámon is ignoring me (the best choice in this case). And its comproved. I can't do a pull request that won't be rated. I'm not asking for assignement on every issue, but in a few of my own issues (not all). Like a close/open/change title marks in a issue, ask for a assignment is a primitive/manual way of marking a point of history in this issue, and it is part of a social network. This is not a flood, and absolutely not a spam. Please study about  these terms and the difference.

**Comment by DaniellMesquito** [comment]
BTW when pull request of Ryan and any message of me be replied, I'll think in stop my current work to dedicate/take initiative of doing a pull request.

**Comment by amatiasq** [comment]
@DaniellMesquito I'm sorry you take this personal. I was expressing my concerns, not trying to change your life. Looks like you're taking Ramon's little availability personal too. What I'm trying to do is precisely to keep the issues free of personal raptures since the issues should be about the code, not people.

Anyway let's not try to foresee the future, please if you feel you want and can implement this please submit a pull request, I've been waiting with enthusiasm for that since you created the first issue. If you feel otherwise you can just not do it, I don't see the point of this rampage.

I also disagree on Github being a social network this is a tool to manage code which happens to have communication features. I think what you did is spam, I'm happy you have a different point of view. That doesn't mean either of us is right.

Finally I read your last comment more than 10 times and still don't understand what you're trying to say.

**Comment by rlamana** [comment]
Thanks to everyone trying to help here and sorry for my late response, as @amatiasq said I'm not as available as I would like to. 

@DaniellMesquito as I've mentioned before, I'm glad to see the interest you have in Ventus and the energy you put out into your project, but I think you misunderstand the purpose of this library and also some of the mechanisms that make Github a great tool to manage these kind of projects.

Most of the feature requests you have submitted here are tasks related to your project, not to Ventus. The way you should handle this (and in general any other Github project) would be to **fork** Ventus and track your own tasks/issues in your forked repository. Keep you work there and when you think it is ready, Ill be glad to review and accept any pull request that fixes or adds new functionality to the library, as long as your proposals are aligned to the purpose of this library.

Please, move these issues to your own repository. Then you'll be free to assign them to whoever you want.

Thanks.
